version: '3.3'
services:
  nginx:
    image: flashspys/nginx-static
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/static
    networks:
      - traefik-public        
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.dirkengels-cv-http.rule=Host(`cv.dirkengels.com`)
        - traefik.http.routers.dirkengels-cv-http.entrypoints=http
        - traefik.http.routers.dirkengels-cv-http.middlewares=https-redirect
        - traefik.http.routers.dirkengels-cv-https.rule=Host(`cv.dirkengels.com`)
        - traefik.http.routers.dirkengels-cv-https.entrypoints=https
        - traefik.http.routers.dirkengels-cv-https.tls=true
        - traefik.http.routers.dirkengels-cv-https.tls.certresolver=le
        - traefik.http.services.dirkengels-cv.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true

